[package]
name = "jvm-resolver"
description = "Format-agnostic dependency resolution algorithm for JVM projects"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["maven", "gradle", "resolver", "dependency", "jvm"]
categories = ["development-tools", "algorithms"]

[dependencies]
jvm-artifact = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
