//! Writer for Gradle version catalog format (libs.versions.toml).
//!
//! This module generates Gradle version catalogs from lockfiles, enabling
//! seamless integration with Gradle projects.
//!
//! # Example
//!
//! ```ignore
//! use antlers_lock::{Lockfile, writer::gradle};
//!
//! let lockfile = Lockfile::read_file("deps.lock.json")?;
//! let toml = gradle::write_gradle_catalog(&lockfile)?;
//! std::fs::write("gradle/libs.versions.toml", toml)?;
//! ```
//!
//! # Format
//!
//! The generated file follows the Gradle version catalog format:
//!
//! ```toml
//! # Generated by antlers
//!
//! [versions]
//! guava = "33.0.0-jre"
//!
//! [libraries]
//! guava = { module = "com.google.guava:guava", version.ref = "guava" }
//!
//! [bundles]
//! # Bundle definitions (if enabled)
//!
//! [plugins]
//! # Plugin definitions (future support)
//! ```

use std::collections::HashMap;
use std::fmt::Write as _;

use indexmap::IndexMap;

use crate::Lockfile;
use crate::error::Result;

/// Options for Gradle catalog generation.
#[derive(Debug, Clone, Default)]
pub struct GradleCatalogOptions {
    /// Whether to generate bundles from dependency relationships.
    pub generate_bundles: bool,
    /// Custom version aliases (artifact coordinate -> alias).
    /// Key is "group:artifact", value is the desired version alias.
    pub version_aliases: HashMap<String, String>,
}

impl GradleCatalogOptions {
    /// Creates new options with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Enables bundle generation.
    #[must_use]
    pub const fn with_bundles(mut self) -> Self {
        self.generate_bundles = true;
        self
    }

    /// Adds a custom version alias.
    #[must_use]
    pub fn with_version_alias(
        mut self,
        coordinate: impl Into<String>,
        alias: impl Into<String>,
    ) -> Self {
        self.version_aliases.insert(coordinate.into(), alias.into());
        self
    }
}

/// Writes a lockfile to Gradle version catalog format.
///
/// Uses default options (no bundles, automatic naming).
///
/// # Errors
///
/// Returns an error if the lockfile contains invalid data.
pub fn write_gradle_catalog(lockfile: &Lockfile) -> Result<String> {
    write_gradle_catalog_with_options(lockfile, &GradleCatalogOptions::default())
}

/// Writes a lockfile to Gradle version catalog format with custom options.
///
/// # Errors
///
/// Returns an error if the lockfile contains invalid data.
pub fn write_gradle_catalog_with_options(
    lockfile: &Lockfile,
    options: &GradleCatalogOptions,
) -> Result<String> {
    let mut output = String::new();

    // Header
    output.push_str("# Generated by antlers\n\n");

    // Build library name mappings and detect conflicts
    let library_names = build_library_names(lockfile);

    // Build version entries with deduplication
    let (versions, library_version_refs) = build_version_entries(lockfile, &library_names, options);

    // Write [versions] section
    output.push_str("[versions]\n");
    if versions.is_empty() {
        output.push_str("# No versions defined\n");
    } else {
        for (alias, version) in &versions {
            let escaped = escape_toml_string(version);
            let _ = writeln!(output, "{alias} = \"{escaped}\"");
        }
    }
    output.push('\n');

    // Write [libraries] section
    output.push_str("[libraries]\n");
    if lockfile.artifacts.is_empty() {
        output.push_str("# No libraries defined\n");
    } else {
        // Sort for deterministic output
        let mut sorted_artifacts: Vec<_> = lockfile.artifacts.iter().collect();
        sorted_artifacts.sort_by(|(k1, _), (k2, _)| k1.cmp(k2));

        for (coord, _artifact) in sorted_artifacts {
            let library_name = library_names.get(coord).unwrap();
            let version_ref = library_version_refs.get(coord).unwrap();

            let _ = writeln!(
                output,
                "{library_name} = {{ module = \"{coord}\", version.ref = \"{version_ref}\" }}"
            );
        }
    }
    output.push('\n');

    // Write [bundles] section
    output.push_str("[bundles]\n");
    if options.generate_bundles {
        let bundles = generate_bundles(lockfile, &library_names);
        if bundles.is_empty() {
            output.push_str("# No bundles generated\n");
        } else {
            for (bundle_name, libraries) in &bundles {
                let libs_str = libraries
                    .iter()
                    .map(|l| format!("\"{l}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(output, "{bundle_name} = [{libs_str}]");
            }
        }
    } else {
        output.push_str("# Bundles group related libraries\n");
        output.push_str("# example = [\"lib1\", \"lib2\"]\n");
    }
    output.push('\n');

    // Write [plugins] section
    output.push_str("[plugins]\n");
    output.push_str("# Plugin declarations (if any)\n");

    Ok(output)
}

/// Builds a mapping from artifact coordinates to library names.
///
/// Handles naming conflicts by prefixing with group information when needed.
fn build_library_names(lockfile: &Lockfile) -> IndexMap<String, String> {
    let mut names: IndexMap<String, String> = IndexMap::new();
    let mut name_counts: HashMap<String, Vec<String>> = HashMap::new();

    // First pass: collect all artifact names and detect conflicts
    for coord in lockfile.artifacts.keys() {
        let artifact_name = extract_artifact_name(coord);
        name_counts
            .entry(artifact_name)
            .or_default()
            .push(coord.clone());
    }

    // Second pass: assign names, handling conflicts
    for coord in lockfile.artifacts.keys() {
        let artifact_name = extract_artifact_name(coord);

        let library_name = if name_counts.get(&artifact_name).is_some_and(|v| v.len() > 1) {
            // Conflict: use group prefix
            make_qualified_name(coord)
        } else {
            // No conflict: use artifact name
            sanitize_toml_key(&artifact_name)
        };

        names.insert(coord.clone(), library_name);
    }

    names
}

/// Extracts the artifact name from a coordinate (group:artifact).
fn extract_artifact_name(coord: &str) -> String {
    coord.split(':').nth(1).unwrap_or(coord).to_string()
}

/// Creates a qualified name from coordinate when there are conflicts.
fn make_qualified_name(coord: &str) -> String {
    let parts: Vec<&str> = coord.split(':').collect();
    if parts.len() >= 2 {
        let group = parts[0];
        let artifact = parts[1];

        // Use the last segment of the group for shorter names
        let group_suffix = group.split('.').next_back().unwrap_or(group);

        sanitize_toml_key(&format!("{group_suffix}-{artifact}"))
    } else {
        sanitize_toml_key(coord)
    }
}

/// Sanitizes a string to be a valid TOML key.
///
/// - Replaces invalid characters with hyphens
/// - Ensures it starts with a letter or underscore
fn sanitize_toml_key(s: &str) -> String {
    let mut result = String::with_capacity(s.len());

    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
            result.push(c);
        } else if c == '.' || c == ':' {
            result.push('-');
        } else {
            // Skip other characters
        }

        // Ensure first character is valid
        if i == 0 && !c.is_ascii_alphabetic() && c != '_' {
            result.insert(0, '_');
        }
    }

    // Handle empty result
    if result.is_empty() {
        return "_unnamed".to_string();
    }

    result
}

/// Escapes a string for TOML value context.
fn escape_toml_string(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(c),
        }
    }
    result
}

/// Builds version entries with deduplication.
///
/// Returns (`version_aliases`, `library_to_version_ref`).
fn build_version_entries(
    lockfile: &Lockfile,
    library_names: &IndexMap<String, String>,
    options: &GradleCatalogOptions,
) -> (IndexMap<String, String>, IndexMap<String, String>) {
    // Group artifacts by version to find shared versions
    let mut version_to_coords: HashMap<String, Vec<String>> = HashMap::new();

    for (coord, artifact) in &lockfile.artifacts {
        version_to_coords
            .entry(artifact.version.clone())
            .or_default()
            .push(coord.clone());
    }

    // Identify groups that share versions (by group prefix)
    let mut group_versions: HashMap<String, (String, Vec<String>)> = HashMap::new();

    for (coord, artifact) in &lockfile.artifacts {
        let group = coord.split(':').next().unwrap_or("");

        group_versions
            .entry(group.to_string())
            .or_insert_with(|| (artifact.version.clone(), Vec::new()))
            .1
            .push(coord.clone());
    }

    // Build version aliases
    let mut versions: IndexMap<String, String> = IndexMap::new();
    let mut library_version_refs: IndexMap<String, String> = IndexMap::new();

    // Check for shared versions within groups
    for (group, (first_version, coords)) in &group_versions {
        let all_same_version = coords.iter().all(|c| {
            lockfile
                .artifacts
                .get(c)
                .is_some_and(|a| a.version == *first_version)
        });

        if all_same_version && coords.len() > 1 {
            // Create a shared version alias for this group
            let version_alias = make_group_version_alias(group);
            versions.insert(version_alias.clone(), first_version.clone());

            for coord in coords {
                library_version_refs.insert(coord.clone(), version_alias.clone());
            }
        } else {
            // Individual version aliases for each artifact
            for coord in coords {
                let artifact = lockfile.artifacts.get(coord).unwrap();
                let library_name = library_names.get(coord).unwrap();

                // Check for custom alias
                let version_alias = options
                    .version_aliases
                    .get(coord)
                    .cloned()
                    .unwrap_or_else(|| library_name.clone());

                versions.insert(version_alias.clone(), artifact.version.clone());
                library_version_refs.insert(coord.clone(), version_alias);
            }
        }
    }

    // Sort versions for deterministic output
    versions.sort_keys();

    (versions, library_version_refs)
}

/// Creates a version alias from a group name.
fn make_group_version_alias(group: &str) -> String {
    // Use the last significant part of the group
    let parts: Vec<&str> = group.split('.').collect();

    // Find a meaningful name, skipping common prefixes like "com", "org", "io"
    let meaningful_parts: Vec<&str> = parts
        .iter()
        .skip_while(|p| matches!(**p, "com" | "org" | "io" | "net" | "dev"))
        .copied()
        .collect();

    let alias = if meaningful_parts.is_empty() {
        parts.last().copied().unwrap_or("version")
    } else if meaningful_parts.len() == 1 {
        meaningful_parts[0]
    } else {
        // Join first two meaningful parts
        return sanitize_toml_key(&format!("{}-{}", meaningful_parts[0], meaningful_parts[1]));
    };

    sanitize_toml_key(alias)
}

/// Generates bundles from dependency relationships.
fn generate_bundles(
    lockfile: &Lockfile,
    library_names: &IndexMap<String, String>,
) -> IndexMap<String, Vec<String>> {
    let mut bundles: IndexMap<String, Vec<String>> = IndexMap::new();

    // Group by group prefix to create bundles
    let mut group_libraries: HashMap<String, Vec<String>> = HashMap::new();

    for coord in lockfile.artifacts.keys() {
        let group = coord.split(':').next().unwrap_or("");
        let library_name = library_names.get(coord).unwrap();
        group_libraries
            .entry(group.to_string())
            .or_default()
            .push(library_name.clone());
    }

    // Only create bundles for groups with multiple libraries
    for (group, libraries) in group_libraries {
        if libraries.len() > 1 {
            let bundle_name = make_group_version_alias(&group);
            let mut sorted_libs = libraries;
            sorted_libs.sort();
            bundles.insert(bundle_name, sorted_libs);
        }
    }

    bundles.sort_keys();
    bundles
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{LockedArtifact, LockfileMetadata};

    fn create_test_lockfile() -> Lockfile {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new("33.0.0-jre", "abc123"),
        );
        artifacts.insert(
            "com.google.guava:failureaccess".to_string(),
            LockedArtifact::new("1.0.2", "def456"),
        );

        Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        }
    }

    #[test]
    fn test_write_simple_catalog() {
        let lockfile = create_test_lockfile();
        let toml = write_gradle_catalog(&lockfile).unwrap();

        assert!(toml.contains("# Generated by antlers"));
        assert!(toml.contains("[versions]"));
        assert!(toml.contains("[libraries]"));
        assert!(toml.contains("[bundles]"));
        assert!(toml.contains("[plugins]"));
    }

    #[test]
    fn test_version_deduplication() {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "org.jetbrains.kotlin:kotlin-stdlib".to_string(),
            LockedArtifact::new("2.0.0", "abc123"),
        );
        artifacts.insert(
            "org.jetbrains.kotlin:kotlin-reflect".to_string(),
            LockedArtifact::new("2.0.0", "def456"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let toml = write_gradle_catalog(&lockfile).unwrap();

        // Should have a shared version for kotlin
        assert!(toml.contains("kotlin"));
        assert!(toml.contains("2.0.0"));

        // Count version.ref occurrences - should reference the same version
        let version_ref_count = toml.matches("version.ref").count();
        assert_eq!(version_ref_count, 2);
    }

    #[test]
    fn test_library_name_generation() {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new("33.0.0-jre", "abc"),
        );
        artifacts.insert(
            "com.fasterxml.jackson.core:jackson-databind".to_string(),
            LockedArtifact::new("2.15.0", "def"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let toml = write_gradle_catalog(&lockfile).unwrap();

        // Should have simple artifact names
        assert!(toml.contains("guava = {"));
        assert!(toml.contains("jackson-databind = {"));
    }

    #[test]
    fn test_conflicting_artifact_names() {
        let mut artifacts = IndexMap::new();
        // Two artifacts with the same artifact name but different groups
        artifacts.insert(
            "org.apache.commons:commons-lang3".to_string(),
            LockedArtifact::new("3.12.0", "abc"),
        );
        artifacts.insert(
            "com.example:commons-lang3".to_string(),
            LockedArtifact::new("1.0.0", "def"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let toml = write_gradle_catalog(&lockfile).unwrap();

        // Should have qualified names to avoid conflict
        assert!(toml.contains("commons-commons-lang3") || toml.contains("example-commons-lang3"));
    }

    #[test]
    fn test_valid_toml_syntax() {
        let lockfile = create_test_lockfile();
        let toml = write_gradle_catalog(&lockfile).unwrap();

        // Basic TOML syntax checks
        assert!(toml.starts_with('#'));
        assert!(toml.contains('['));
        assert!(toml.contains(']'));
        assert!(toml.contains('='));

        // All string values should be quoted
        for line in toml.lines() {
            if line.contains(" = \"") {
                assert!(line.ends_with('"') || line.ends_with('}'));
            }
        }
    }

    #[test]
    fn test_special_characters_in_names() {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.example:my.artifact.name".to_string(),
            LockedArtifact::new("1.0.0", "abc"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let toml = write_gradle_catalog(&lockfile).unwrap();

        // Should have sanitized name (dots replaced with hyphens)
        assert!(toml.contains("my-artifact-name") || toml.contains("my_artifact_name"));
    }

    #[test]
    fn test_bundle_generation() {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new("33.0.0-jre", "abc"),
        );
        artifacts.insert(
            "com.google.guava:failureaccess".to_string(),
            LockedArtifact::new("1.0.2", "def"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let options = GradleCatalogOptions::new().with_bundles();
        let toml = write_gradle_catalog_with_options(&lockfile, &options).unwrap();

        // Should have a bundle for google/guava
        assert!(toml.contains("[bundles]"));
        assert!(toml.contains("guava") && toml.contains("failureaccess"));
    }

    #[test]
    fn test_custom_version_alias() {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new("33.0.0-jre", "abc"),
        );

        let lockfile = Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        };

        let options = GradleCatalogOptions::new()
            .with_version_alias("com.google.guava:guava", "guavaVersion");

        let toml = write_gradle_catalog_with_options(&lockfile, &options).unwrap();

        assert!(toml.contains("guavaVersion = \"33.0.0-jre\""));
        assert!(toml.contains("version.ref = \"guavaVersion\""));
    }

    #[test]
    fn test_empty_lockfile() {
        let lockfile = Lockfile::new();
        let toml = write_gradle_catalog(&lockfile).unwrap();

        assert!(toml.contains("[versions]"));
        assert!(toml.contains("[libraries]"));
        assert!(toml.contains("# No versions defined") || toml.contains("# No libraries defined"));
    }

    #[test]
    fn test_escape_toml_string() {
        assert_eq!(escape_toml_string("simple"), "simple");
        assert_eq!(escape_toml_string("with\"quotes"), "with\\\"quotes");
        assert_eq!(escape_toml_string("with\\backslash"), "with\\\\backslash");
        assert_eq!(escape_toml_string("with\nnewline"), "with\\nnewline");
    }

    #[test]
    fn test_sanitize_toml_key() {
        assert_eq!(sanitize_toml_key("simple"), "simple");
        assert_eq!(sanitize_toml_key("with-hyphen"), "with-hyphen");
        assert_eq!(sanitize_toml_key("with.dot"), "with-dot");
        assert_eq!(sanitize_toml_key("with:colon"), "with-colon");
        assert_eq!(sanitize_toml_key("123numeric"), "_123numeric");
    }

    #[test]
    fn test_extract_artifact_name() {
        assert_eq!(extract_artifact_name("com.google.guava:guava"), "guava");
        assert_eq!(
            extract_artifact_name("org.jetbrains.kotlin:kotlin-stdlib"),
            "kotlin-stdlib"
        );
    }
}
