//! Starlark writers for Bazel compatibility.
//!
//! This module provides writers for generating Starlark files from lockfiles:
//!
//! - [`write_starlark_dict`] - PACKAGES-style data structure for simple data access
//! - [`write_module_extension`] - bzlmod MODULE.bazel compatible extension
//! - [`write_starlark_macro`] - Legacy WORKSPACE-compatible repositories.bzl
//!
//! # Dict Format Example
//!
//! ```ignore
//! use antlers_lock::{Lockfile, writer::starlark};
//!
//! let lockfile = Lockfile::read_file("deps.lock.json")?;
//! let bzl = starlark::write_starlark_dict(&lockfile)?;
//! std::fs::write("maven_artifacts.bzl", bzl)?;
//! ```
//!
//! The dict format generates PACKAGES-style data structures:
//!
//! ```starlark
//! """Maven artifact definitions generated by antlers."""
//!
//! MAVEN_CENTRAL = "https://repo1.maven.org/maven2"
//!
//! ARTIFACTS = {
//!     "com.google.guava:guava": {
//!         "33.0.0-jre": {
//!             "path": "com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar",
//!             "sha256": "abc123...",
//!         },
//!     },
//! }
//!
//! MAVEN_ARTIFACTS = [
//!     {"coord": "com.google.guava:guava:33.0.0-jre", "sha256": "abc123...", "deps": []},
//! ]
//! ```
//!
//! # Module Extension Example
//!
//! ```ignore
//! use antlers_lock::{Lockfile, writer::starlark};
//!
//! let lockfile = Lockfile::read_file("deps.lock.json")?;
//! let bzl = starlark::write_module_extension(&lockfile)?;
//! std::fs::write("maven.bzl", bzl)?;
//! ```
//!
//! Usage in MODULE.bazel:
//!
//! ```starlark
//! maven = use_extension("//:maven.bzl", "maven")
//! maven.install()
//! use_repo(maven, "com_google_guava_guava", "org_jetbrains_kotlin_kotlin_stdlib")
//! ```
//!
//! # Macro Format Example (Legacy WORKSPACE)
//!
//! ```ignore
//! use antlers_lock::{Lockfile, writer::starlark};
//!
//! let lockfile = Lockfile::read_file("deps.lock.json")?;
//! let bzl = starlark::write_starlark_macro(&lockfile)?;
//! std::fs::write("repositories.bzl", bzl)?;
//! ```
//!
//! Usage in WORKSPACE:
//!
//! ```starlark
//! load("//:repositories.bzl", "maven_dependencies")
//! maven_dependencies()
//! ```
//!
//! The macro format generates:
//!
//! ```starlark
//! """Maven dependencies for WORKSPACE."""
//!
//! load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")
//!
//! def maybe(repo_rule, name, **kwargs):
//!     if name not in native.existing_rules():
//!         repo_rule(name = name, **kwargs)
//!
//! def _download(name, path, sha256):
//!     maybe(http_jar, name = name, url = "https://repo1.maven.org/maven2/" + path, sha256 = sha256)
//!
//! def maven_dependencies():
//!     _download(name = "com_google_guava_guava", path = "...", sha256 = "...")
//! ```

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde::Serialize;
// serde_starlark is used for proper Starlark AST serialization

use crate::Lockfile;
use crate::error::Result;

// =============================================================================
// Starlark AST Types (serde-serializable)
// =============================================================================

// For dict output, we use BTreeMap directly since serde_starlark serializes
// maps as Starlark dicts. Named structs would serialize as function calls.

/// Represents a value that can be serialized to Starlark.
/// This enum allows mixing strings and arrays in dict values.
#[derive(Debug, Clone, Serialize)]
#[serde(untagged)]
enum StarlarkValue {
    String(String),
    Array(Vec<String>),
}

/// A `_download()` function call for the macro format.
/// Serializes to: `_download(name = "...", path = "...", sha256 = "...")`
#[derive(Debug, Clone, Serialize)]
#[serde(rename = "_download")]
struct DownloadCall {
    name: String,
    path: String,
    sha256: String,
}

/// Default Maven Central repository URL.
pub const MAVEN_CENTRAL_URL: &str = "https://repo1.maven.org/maven2";

// =============================================================================
// Dict Format (PACKAGES-style data structures)
// =============================================================================

/// Options for customizing Starlark dict output.
#[derive(Debug, Clone)]
pub struct StarlarkDictOptions {
    /// Repository URL (default: Maven Central).
    pub repository_url: String,
    /// Include dependencies in output (default: true).
    pub include_deps: bool,
    /// Variable name for the nested dict (default: "ARTIFACTS").
    pub dict_name: String,
    /// Variable name for the flat list (default: `MAVEN_ARTIFACTS`).
    pub list_name: String,
    /// Include the flat list format (default: true).
    pub include_flat_list: bool,
    /// Include repository URL constant (default: true).
    pub include_repo_constant: bool,
}

impl Default for StarlarkDictOptions {
    fn default() -> Self {
        Self {
            repository_url: MAVEN_CENTRAL_URL.to_string(),
            include_deps: true,
            dict_name: "ARTIFACTS".to_string(),
            list_name: "MAVEN_ARTIFACTS".to_string(),
            include_flat_list: true,
            include_repo_constant: true,
        }
    }
}

impl StarlarkDictOptions {
    /// Creates options with a custom repository URL.
    #[must_use]
    pub fn with_repository_url(mut self, url: impl Into<String>) -> Self {
        self.repository_url = url.into();
        self
    }

    /// Sets whether to include dependencies.
    #[must_use]
    pub const fn with_include_deps(mut self, include: bool) -> Self {
        self.include_deps = include;
        self
    }

    /// Sets the variable name for the nested dict.
    #[must_use]
    pub fn with_dict_name(mut self, name: impl Into<String>) -> Self {
        self.dict_name = name.into();
        self
    }

    /// Sets the variable name for the flat list.
    #[must_use]
    pub fn with_list_name(mut self, name: impl Into<String>) -> Self {
        self.list_name = name.into();
        self
    }

    /// Sets whether to include the flat list format.
    #[must_use]
    pub const fn with_include_flat_list(mut self, include: bool) -> Self {
        self.include_flat_list = include;
        self
    }

    /// Sets whether to include the repository URL constant.
    #[must_use]
    pub const fn with_include_repo_constant(mut self, include: bool) -> Self {
        self.include_repo_constant = include;
        self
    }
}

/// Writes a lockfile to Starlark dict format with default options.
///
/// Generates a PACKAGES-style data structure with:
/// - A nested dict indexed by `group:artifact`, then version
/// - A flat list for simpler iteration
///
/// # Example
///
/// ```ignore
/// use antlers_lock::{Lockfile, writer};
///
/// let lockfile = Lockfile::read_file("deps.lock.json")?;
/// let starlark = writer::write_starlark_dict(&lockfile)?;
/// std::fs::write("maven_deps.bzl", starlark)?;
/// ```
///
/// # Errors
///
/// This function is infallible in practice as writing to a String never fails.
pub fn write_starlark_dict(lockfile: &Lockfile) -> Result<String> {
    write_starlark_dict_with_options(lockfile, &StarlarkDictOptions::default())
}

/// Writes a lockfile to Starlark dict format with custom options.
///
/// # Example
///
/// ```ignore
/// use antlers_lock::{Lockfile, writer::{self, StarlarkDictOptions}};
///
/// let lockfile = Lockfile::read_file("deps.lock.json")?;
/// let options = StarlarkDictOptions::default()
///     .with_dict_name("PACKAGES")
///     .with_include_deps(false);
/// let starlark = writer::write_starlark_dict_with_options(&lockfile, &options)?;
/// ```
///
/// # Errors
///
/// This function is infallible in practice as writing to a String never fails.
#[allow(clippy::unnecessary_wraps)]
pub fn write_starlark_dict_with_options(
    lockfile: &Lockfile,
    options: &StarlarkDictOptions,
) -> Result<String> {
    let mut output = String::new();

    // Write docstring
    output.push_str("\"\"\"Maven artifact definitions generated by antlers.\"\"\"\n\n");

    // Write repository URL constant using serde_starlark
    if options.include_repo_constant {
        let assignment =
            serde_starlark::Assignment::new("MAVEN_CENTRAL", options.repository_url.as_str());
        output.push_str(&serde_starlark::to_string(&assignment).unwrap_or_else(|_| String::new()));
        output.push('\n');
    }

    // Write nested dict (ARTIFACTS)
    write_nested_dict(&mut output, lockfile, options);

    // Write flat list (MAVEN_ARTIFACTS)
    if options.include_flat_list {
        output.push('\n');
        write_flat_list(&mut output, lockfile, options);
    }

    Ok(output)
}

/// Builds the nested dict structure for artifacts.
/// Returns a nested `BTreeMap` that serializes to Starlark dict syntax.
fn build_nested_dict(
    lockfile: &Lockfile,
    options: &StarlarkDictOptions,
) -> BTreeMap<String, BTreeMap<String, BTreeMap<String, StarlarkValue>>> {
    let mut result: BTreeMap<String, BTreeMap<String, BTreeMap<String, StarlarkValue>>> =
        BTreeMap::new();

    for (key, artifact) in &lockfile.artifacts {
        let path = build_maven_path_with_classifier(
            key,
            &artifact.version,
            &artifact.packaging,
            artifact.classifier.as_deref(),
        );

        // Build version info as a BTreeMap for proper dict serialization
        let mut version_info: BTreeMap<String, StarlarkValue> = BTreeMap::new();
        version_info.insert("path".to_string(), StarlarkValue::String(path));
        version_info.insert(
            "sha256".to_string(),
            StarlarkValue::String(artifact.sha256.clone()),
        );

        // Only include deps if enabled and non-empty
        if options.include_deps && !artifact.dependencies.is_empty() {
            let deps_with_versions: Vec<String> = artifact
                .dependencies
                .iter()
                .filter_map(|dep_key| {
                    lockfile
                        .artifacts
                        .get(dep_key)
                        .map(|dep_artifact| format!("{}:{}", dep_key, dep_artifact.version))
                })
                .collect();
            version_info.insert("deps".to_string(), StarlarkValue::Array(deps_with_versions));
        }

        let version_map = result.entry(key.clone()).or_default();
        version_map.insert(artifact.version.clone(), version_info);
    }

    result
}

/// Writes the nested dict format indexed by group:artifact, then version.
fn write_nested_dict(output: &mut String, lockfile: &Lockfile, options: &StarlarkDictOptions) {
    output.push_str("# Artifact metadata indexed by group:artifact, then version\n");

    let nested_dict = build_nested_dict(lockfile, options);
    let assignment = serde_starlark::Assignment::new(options.dict_name.as_str(), &nested_dict);

    output.push_str(&serde_starlark::to_string(&assignment).unwrap_or_else(|_| {
        // Fallback to empty dict on serialization error
        format!("{} = {{}}\n", options.dict_name)
    }));
}

/// Builds the flat list of artifacts.
/// Returns a `Vec` of `BTreeMap`s that serialize to Starlark dict entries.
fn build_flat_list(
    lockfile: &Lockfile,
    options: &StarlarkDictOptions,
) -> Vec<BTreeMap<String, StarlarkValue>> {
    lockfile
        .artifacts
        .iter()
        .map(|(key, artifact)| {
            let coord = format!("{}:{}", key, artifact.version);

            let mut entry: BTreeMap<String, StarlarkValue> = BTreeMap::new();
            entry.insert("coord".to_string(), StarlarkValue::String(coord));
            entry.insert(
                "sha256".to_string(),
                StarlarkValue::String(artifact.sha256.clone()),
            );

            if options.include_deps {
                let deps_with_versions: Vec<String> = artifact
                    .dependencies
                    .iter()
                    .filter_map(|dep_key| {
                        lockfile
                            .artifacts
                            .get(dep_key)
                            .map(|dep_artifact| format!("{}:{}", dep_key, dep_artifact.version))
                    })
                    .collect();
                entry.insert("deps".to_string(), StarlarkValue::Array(deps_with_versions));
            }

            entry
        })
        .collect()
}

/// Writes the flat list format for simpler iteration.
fn write_flat_list(output: &mut String, lockfile: &Lockfile, options: &StarlarkDictOptions) {
    output.push_str("# Flat list for simpler iteration\n");

    let flat_list = build_flat_list(lockfile, options);
    let assignment = serde_starlark::Assignment::new(options.list_name.as_str(), &flat_list);

    output.push_str(&serde_starlark::to_string(&assignment).unwrap_or_else(|_| {
        // Fallback to empty list on serialization error
        format!("{} = []\n", options.list_name)
    }));
}

/// Builds a Maven-style path for an artifact with classifier support.
///
/// Format: `group/as/path/artifact/version/artifact-version[-classifier].extension`
fn build_maven_path_with_classifier(
    key: &str,
    version: &str,
    packaging: &str,
    classifier: Option<&str>,
) -> String {
    let parts: Vec<&str> = key.split(':').collect();
    if parts.len() != 2 {
        return String::new();
    }

    let group = parts[0];
    let artifact_id = parts[1];

    // Convert group to path (e.g., "org.example" -> "org/example")
    let group_path = group.replace('.', "/");

    // Build filename
    let filename = classifier.map_or_else(
        || format!("{artifact_id}-{version}.{packaging}"),
        |c| format!("{artifact_id}-{version}-{c}.{packaging}"),
    );

    format!("{group_path}/{artifact_id}/{version}/{filename}")
}

// =============================================================================
// Module Extension Format (bzlmod)
// =============================================================================

/// Options for module extension generation.
#[derive(Debug, Clone)]
pub struct ModuleExtensionOptions {
    /// Extension name (default: "maven").
    pub extension_name: String,
    /// Repository URL (default: Maven Central).
    pub repository_url: String,
    /// Whether to include detailed doc comments.
    pub include_docs: bool,
}

impl Default for ModuleExtensionOptions {
    fn default() -> Self {
        Self {
            extension_name: "maven".to_string(),
            repository_url: MAVEN_CENTRAL_URL.to_string(),
            include_docs: true,
        }
    }
}

impl ModuleExtensionOptions {
    /// Creates new options with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the extension name.
    #[must_use]
    pub fn with_extension_name(mut self, name: impl Into<String>) -> Self {
        self.extension_name = name.into();
        self
    }

    /// Sets the repository URL.
    #[must_use]
    pub fn with_repository_url(mut self, url: impl Into<String>) -> Self {
        self.repository_url = url.into();
        self
    }

    /// Disables doc comments in the output.
    #[must_use]
    pub const fn without_docs(mut self) -> Self {
        self.include_docs = false;
        self
    }
}

/// Writes a lockfile to a bzlmod module extension format.
///
/// Uses default options (extension name "maven", Maven Central repository).
///
/// # Errors
///
/// Returns an error if the lockfile contains invalid data.
pub fn write_module_extension(lockfile: &Lockfile) -> Result<String> {
    write_module_extension_with_options(lockfile, &ModuleExtensionOptions::default())
}

/// Writes a lockfile to a bzlmod module extension format with custom options.
///
/// # Errors
///
/// Returns an error if the lockfile contains invalid data.
#[allow(clippy::unnecessary_wraps)]
pub fn write_module_extension_with_options(
    lockfile: &Lockfile,
    options: &ModuleExtensionOptions,
) -> Result<String> {
    let mut output = String::new();

    // Header with module docstring
    if options.include_docs {
        output.push_str("\"\"\"Maven module extension for bzlmod.\n\n");
        output.push_str("This file is generated by antlers. Do not edit manually.\n");
        output.push_str("\"\"\"\n\n");
    } else {
        output.push_str("# Generated by antlers\n\n");
    }

    // Load statement for http_jar
    output.push_str("load(\"@bazel_tools//tools/build_defs/repo:http.bzl\", \"http_jar\")\n\n");

    // Repository constant
    let _ = writeln!(
        output,
        "_MAVEN_REPOSITORY = \"{}\"",
        escape_starlark(&options.repository_url)
    );
    output.push('\n');

    // Write the pinned artifacts dictionary
    write_pinned_artifacts(&mut output, lockfile, options);
    output.push('\n');

    // Write the tag_class for install
    write_install_tag_class(&mut output, options);
    output.push('\n');

    // Write the implementation function
    write_impl_function(&mut output, options);
    output.push('\n');

    // Write the module_extension declaration
    write_extension_declaration(&mut output, options);
    output.push('\n');

    // Write usage comment showing use_repo
    write_usage_comment(&mut output, lockfile, options);

    Ok(output)
}

/// Builds a pinned artifact entry as a `BTreeMap` for proper dict serialization.
fn build_pinned_artifact_entry(
    lockfile: &Lockfile,
    coord: &str,
    artifact: &crate::LockedArtifact,
    options: &ModuleExtensionOptions,
) -> BTreeMap<String, StarlarkValue> {
    let repo_name = coordinate_to_repo_name(coord);
    let path = coordinate_to_path(coord, &artifact.version, &artifact.packaging);

    let mut entry: BTreeMap<String, StarlarkValue> = BTreeMap::new();

    // Add required fields in alphabetical order (BTreeMap will sort them)
    let deps: Vec<String> = artifact
        .dependencies
        .iter()
        .map(|dep| {
            let dep_version = lockfile
                .artifacts
                .get(dep)
                .map_or("*", |a| a.version.as_str());
            format!("{dep}:{dep_version}")
        })
        .collect();

    entry.insert("deps".to_string(), StarlarkValue::Array(deps));
    entry.insert("name".to_string(), StarlarkValue::String(repo_name));
    entry.insert("path".to_string(), StarlarkValue::String(path));
    entry.insert(
        "sha256".to_string(),
        StarlarkValue::String(artifact.sha256.clone()),
    );

    // Add repository URL if different from default
    if let Some(ref repo) = artifact.repository {
        let repo_url = repo.trim_end_matches('/');
        let default_url = options.repository_url.trim_end_matches('/');
        if repo_url != default_url {
            entry.insert(
                "repository".to_string(),
                StarlarkValue::String(repo.clone()),
            );
        }
    }

    entry
}

/// Writes the `_PINNED_ARTIFACTS` dictionary using `serde_starlark`.
fn write_pinned_artifacts(
    output: &mut String,
    lockfile: &Lockfile,
    options: &ModuleExtensionOptions,
) {
    // Build the pinned artifacts dict
    let mut pinned: BTreeMap<String, BTreeMap<String, StarlarkValue>> = BTreeMap::new();

    for (coord, artifact) in &lockfile.artifacts {
        let key = format!("{}:{}", coord, artifact.version);
        let entry = build_pinned_artifact_entry(lockfile, coord, artifact, options);
        pinned.insert(key, entry);
    }

    // Serialize using serde_starlark for proper formatting
    let assignment = serde_starlark::Assignment::new("_PINNED_ARTIFACTS", &pinned);
    output.push_str(
        &serde_starlark::to_string(&assignment)
            .unwrap_or_else(|_| "_PINNED_ARTIFACTS = {}\n".to_string()),
    );
}

/// Writes the `_install` `tag_class`.
fn write_install_tag_class(output: &mut String, options: &ModuleExtensionOptions) {
    output.push_str("_install = tag_class(\n");

    if options.include_docs {
        output.push_str("    doc = \"Install pinned Maven dependencies.\",\n");
    }

    output.push_str("    attrs = {\n");
    output.push_str("        \"artifacts\": attr.string_list(\n");

    if options.include_docs {
        output.push_str(
            "            doc = \"Artifact coordinates to install (group:artifact:version). Empty means all.\",\n",
        );
    }

    output.push_str("            default = [],\n");
    output.push_str("        ),\n");
    output.push_str("        \"repository\": attr.string(\n");

    if options.include_docs {
        output.push_str("            doc = \"Maven repository URL.\",\n");
    }

    output.push_str("            default = _MAVEN_REPOSITORY,\n");
    output.push_str("        ),\n");
    output.push_str("    },\n");
    output.push_str(")\n");
}

/// Writes the implementation function.
fn write_impl_function(output: &mut String, options: &ModuleExtensionOptions) {
    let _ = writeln!(output, "def _{}_impl(module_ctx):", options.extension_name);

    if options.include_docs {
        let _ = writeln!(
            output,
            "    \"\"\"Implementation of the {} module extension.\"\"\"",
            options.extension_name
        );
    }

    output.push_str("    artifacts_to_install = {}\n\n");

    // Module iteration
    output.push_str("    for mod in module_ctx.modules:\n");
    output.push_str("        for install in mod.tags.install:\n");
    output.push_str(
        "            coords = install.artifacts if install.artifacts else _PINNED_ARTIFACTS.keys()\n",
    );
    output.push_str("            for coord in coords:\n");
    output.push_str("                if coord in _PINNED_ARTIFACTS:\n");
    output.push_str("                    artifacts_to_install[coord] = _PINNED_ARTIFACTS[coord]\n");
    output.push('\n');

    // Create http_jar rules
    output.push_str("    for coord, info in artifacts_to_install.items():\n");
    output.push_str("        repo_url = info.get(\"repository\", _MAVEN_REPOSITORY)\n");
    output.push_str("        http_jar(\n");
    output.push_str("            name = info[\"name\"],\n");
    output.push_str("            url = repo_url.rstrip(\"/\") + \"/\" + info[\"path\"],\n");
    output.push_str("            sha256 = info[\"sha256\"],\n");
    output.push_str("        )\n");
}

/// Writes the `module_extension` declaration.
fn write_extension_declaration(output: &mut String, options: &ModuleExtensionOptions) {
    let _ = writeln!(output, "{} = module_extension(", options.extension_name);

    if options.include_docs {
        output.push_str("    doc = \"Maven dependency management from pinned lockfile.\",\n");
    }

    let _ = writeln!(
        output,
        "    implementation = _{}_impl,",
        options.extension_name
    );
    output.push_str("    tag_classes = {\n");
    output.push_str("        \"install\": _install,\n");
    output.push_str("    },\n");
    output.push_str(")\n");
}

/// Writes a comment showing how to use the extension in MODULE.bazel.
fn write_usage_comment(output: &mut String, lockfile: &Lockfile, options: &ModuleExtensionOptions) {
    output.push_str("# Usage in MODULE.bazel:\n");
    output.push_str("# \n");
    let _ = writeln!(
        output,
        "# {} = use_extension(\"//:maven.bzl\", \"{}\")",
        options.extension_name, options.extension_name
    );
    let _ = writeln!(output, "# {}.install()", options.extension_name);

    // Build the use_repo line with all artifact names
    let mut repo_names: Vec<String> = lockfile
        .artifacts
        .keys()
        .map(|coord| coordinate_to_repo_name(coord))
        .collect();
    repo_names.sort();

    if repo_names.is_empty() {
        let _ = writeln!(output, "# use_repo({}, ...)", options.extension_name);
    } else if repo_names.len() <= 3 {
        let names = repo_names
            .iter()
            .map(|n| format!("\"{n}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(output, "# use_repo({}, {})", options.extension_name, names);
    } else {
        let _ = writeln!(output, "# use_repo(");
        let _ = writeln!(output, "#     {},", options.extension_name);
        for name in &repo_names {
            let _ = writeln!(output, "#     \"{name}\",");
        }
        output.push_str("# )\n");
    }
}

/// Converts a Maven coordinate to a Bazel repository name.
///
/// Example: `com.google.guava:guava` -> `com_google_guava_guava`
fn coordinate_to_repo_name(coord: &str) -> String {
    coord
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Converts a Maven coordinate to a repository path.
///
/// Example: "com.google.guava:guava", "33.0.0-jre", "jar"
///       -> "com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar"
fn coordinate_to_path(coord: &str, version: &str, packaging: &str) -> String {
    let parts: Vec<&str> = coord.split(':').collect();
    if parts.len() < 2 {
        return String::new();
    }

    let group = parts[0];
    let artifact = parts[1];
    let extension = if packaging.is_empty() {
        "jar"
    } else {
        packaging
    };

    let group_path = group.replace('.', "/");
    format!("{group_path}/{artifact}/{version}/{artifact}-{version}.{extension}")
}

/// Escapes a string for Starlark context.
fn escape_starlark(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{LockedArtifact, LockfileMetadata};
    use indexmap::IndexMap;

    fn create_test_lockfile() -> Lockfile {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new(
                "33.0.0-jre",
                "abc123def456789012345678901234567890123456789012345678901234",
            )
            .with_dependencies(vec!["com.google.guava:failureaccess".to_string()]),
        );
        artifacts.insert(
            "com.google.guava:failureaccess".to_string(),
            LockedArtifact::new(
                "1.0.2",
                "def456abc789012345678901234567890123456789012345678901234567",
            ),
        );

        Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        }
    }

    // ==========================================================================
    // Dict Writer Tests
    // ==========================================================================

    #[test]
    fn test_write_starlark_dict_basic() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_dict(&lockfile).unwrap();

        // Check docstring
        assert!(output.contains("\"\"\"Maven artifact definitions generated by antlers.\"\"\""));

        // Check repository constant
        assert!(output.contains("MAVEN_CENTRAL = \"https://repo1.maven.org/maven2\""));

        // Check nested dict
        assert!(output.contains("ARTIFACTS = {"));
        assert!(output.contains("\"com.google.guava:guava\":"));
        assert!(output.contains("\"33.0.0-jre\":"));

        // Check flat list
        assert!(output.contains("MAVEN_ARTIFACTS = ["));
        assert!(output.contains("\"coord\": \"com.google.guava:guava:33.0.0-jre\""));
    }

    #[test]
    fn test_write_starlark_dict_paths() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_dict(&lockfile).unwrap();

        // Check Maven path format
        assert!(
            output.contains("\"path\": \"com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar\"")
        );
        assert!(output.contains(
            "\"path\": \"com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar\""
        ));
    }

    #[test]
    fn test_write_starlark_dict_sha256() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_dict(&lockfile).unwrap();

        assert!(output.contains("\"sha256\": \"abc123def456"));
        assert!(output.contains("\"sha256\": \"def456abc789"));
    }

    #[test]
    fn test_write_starlark_dict_dependencies() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_dict(&lockfile).unwrap();

        // Check dependencies in nested dict
        assert!(output.contains("\"deps\": [\"com.google.guava:failureaccess:1.0.2\"]"));
    }

    #[test]
    fn test_write_starlark_dict_with_options() {
        let lockfile = create_test_lockfile();
        let options = StarlarkDictOptions::default()
            .with_dict_name("PACKAGES")
            .with_list_name("ALL_ARTIFACTS")
            .with_include_deps(false);

        let output = write_starlark_dict_with_options(&lockfile, &options).unwrap();

        assert!(output.contains("PACKAGES = {"));
        assert!(output.contains("ALL_ARTIFACTS = ["));
        assert!(!output.contains("\"deps\":"));
    }

    #[test]
    fn test_write_starlark_dict_no_flat_list() {
        let lockfile = create_test_lockfile();
        let options = StarlarkDictOptions::default().with_include_flat_list(false);

        let output = write_starlark_dict_with_options(&lockfile, &options).unwrap();

        assert!(output.contains("ARTIFACTS = {"));
        assert!(!output.contains("MAVEN_ARTIFACTS = ["));
    }

    #[test]
    fn test_write_starlark_dict_no_repo_constant() {
        let lockfile = create_test_lockfile();
        let options = StarlarkDictOptions::default().with_include_repo_constant(false);

        let output = write_starlark_dict_with_options(&lockfile, &options).unwrap();

        assert!(!output.contains("MAVEN_CENTRAL ="));
    }

    #[test]
    fn test_write_starlark_dict_custom_repo() {
        let lockfile = create_test_lockfile();
        let options =
            StarlarkDictOptions::default().with_repository_url("https://custom.repo.com/maven2");

        let output = write_starlark_dict_with_options(&lockfile, &options).unwrap();

        assert!(output.contains("MAVEN_CENTRAL = \"https://custom.repo.com/maven2\""));
    }

    #[test]
    fn test_write_starlark_dict_empty_lockfile() {
        let lockfile = Lockfile::new();
        let output = write_starlark_dict(&lockfile).unwrap();

        assert!(output.contains("ARTIFACTS = {"));
        assert!(output.contains('}'));
        assert!(output.contains("MAVEN_ARTIFACTS = ["));
        assert!(output.contains(']'));
    }

    #[test]
    fn test_write_starlark_dict_with_classifier() {
        let mut lockfile = Lockfile::new();

        let sources = LockedArtifact::new("1.0.0", "abc123").with_classifier("sources");

        lockfile.insert("org.example:lib".to_string(), sources);

        let output = write_starlark_dict(&lockfile).unwrap();

        // Check path includes classifier
        assert!(output.contains("\"path\": \"org/example/lib/1.0.0/lib-1.0.0-sources.jar\""));
    }

    #[test]
    fn test_write_starlark_dict_aar_packaging() {
        let mut lockfile = Lockfile::new();

        let aar = LockedArtifact::new("1.0.0", "abc123").with_packaging("aar");

        lockfile.insert("com.android:lib".to_string(), aar);

        let output = write_starlark_dict(&lockfile).unwrap();

        // Check path has .aar extension
        assert!(output.contains("\"path\": \"com/android/lib/1.0.0/lib-1.0.0.aar\""));
    }

    #[test]
    fn test_starlark_dict_syntax_valid() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_dict(&lockfile).unwrap();

        // Check for proper Starlark syntax patterns
        assert!(output.contains('{'));
        assert!(output.contains('}'));
        assert!(output.contains('['));
        assert!(output.contains(']'));

        // Check balanced braces (basic check)
        let open_braces = output.matches('{').count();
        let close_braces = output.matches('}').count();
        assert_eq!(open_braces, close_braces);

        let open_brackets = output.matches('[').count();
        let close_brackets = output.matches(']').count();
        assert_eq!(open_brackets, close_brackets);
    }

    #[test]
    fn test_build_maven_path_with_classifier() {
        assert_eq!(
            build_maven_path_with_classifier("com.google.guava:guava", "33.0.0-jre", "jar", None),
            "com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar"
        );

        assert_eq!(
            build_maven_path_with_classifier("org.example:lib", "1.0.0", "jar", Some("sources")),
            "org/example/lib/1.0.0/lib-1.0.0-sources.jar"
        );

        assert_eq!(
            build_maven_path_with_classifier("com.android:lib", "2.0.0", "aar", None),
            "com/android/lib/2.0.0/lib-2.0.0.aar"
        );
    }

    // ==========================================================================
    // Module Extension Writer Tests
    // ==========================================================================

    #[test]
    fn test_write_module_extension() {
        let lockfile = create_test_lockfile();
        let bzl = write_module_extension(&lockfile).unwrap();

        // Check header
        assert!(bzl.contains("Maven module extension for bzlmod"));
        assert!(bzl.contains("generated by antlers"));

        // Check load statement
        assert!(
            bzl.contains("load(\"@bazel_tools//tools/build_defs/repo:http.bzl\", \"http_jar\")")
        );

        // Check repository constant
        assert!(bzl.contains("_MAVEN_REPOSITORY = \"https://repo1.maven.org/maven2\""));

        // Check pinned artifacts
        assert!(bzl.contains("_PINNED_ARTIFACTS = {"));
        assert!(bzl.contains("\"com.google.guava:guava:33.0.0-jre\""));
        assert!(bzl.contains("\"name\": \"com_google_guava_guava\""));
        assert!(
            bzl.contains("\"path\": \"com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar\"")
        );
        assert!(bzl.contains("\"sha256\": \"abc123"));

        // Check tag_class
        assert!(bzl.contains("_install = tag_class("));
        assert!(bzl.contains("\"artifacts\": attr.string_list("));
        assert!(bzl.contains("\"repository\": attr.string("));

        // Check implementation function
        assert!(bzl.contains("def _maven_impl(module_ctx):"));
        assert!(bzl.contains("for mod in module_ctx.modules:"));
        assert!(bzl.contains("for install in mod.tags.install:"));
        assert!(bzl.contains("http_jar("));

        // Check extension declaration
        assert!(bzl.contains("maven = module_extension("));
        assert!(bzl.contains("implementation = _maven_impl,"));
        assert!(bzl.contains("\"install\": _install,"));

        // Check usage comment
        assert!(bzl.contains("# Usage in MODULE.bazel:"));
        assert!(bzl.contains("use_extension"));
        assert!(bzl.contains("use_repo"));
    }

    #[test]
    fn test_coordinate_to_repo_name() {
        assert_eq!(
            coordinate_to_repo_name("com.google.guava:guava"),
            "com_google_guava_guava"
        );
        assert_eq!(
            coordinate_to_repo_name("org.jetbrains.kotlin:kotlin-stdlib"),
            "org_jetbrains_kotlin_kotlin_stdlib"
        );
    }

    #[test]
    fn test_coordinate_to_path() {
        assert_eq!(
            coordinate_to_path("com.google.guava:guava", "33.0.0-jre", "jar"),
            "com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar"
        );
        assert_eq!(
            coordinate_to_path("org.jetbrains.kotlin:kotlin-stdlib", "2.0.0", "jar"),
            "org/jetbrains/kotlin/kotlin-stdlib/2.0.0/kotlin-stdlib-2.0.0.jar"
        );
        // Test with empty packaging defaults to jar
        assert_eq!(
            coordinate_to_path("com.example:lib", "1.0", ""),
            "com/example/lib/1.0/lib-1.0.jar"
        );
    }

    #[test]
    fn test_escape_starlark() {
        assert_eq!(escape_starlark("simple"), "simple");
        assert_eq!(escape_starlark("with\"quote"), "with\\\"quote");
        assert_eq!(escape_starlark("with\\backslash"), "with\\\\backslash");
    }

    #[test]
    fn test_empty_lockfile_module_ext() {
        let lockfile = Lockfile::new();
        let bzl = write_module_extension(&lockfile).unwrap();

        // Should still produce valid output
        assert!(bzl.contains("_PINNED_ARTIFACTS = {"));
        assert!(bzl.contains("maven = module_extension("));
    }
}

// =============================================================================
// Starlark Macro Writer (Legacy WORKSPACE-compatible repositories.bzl)
// =============================================================================

/// Options for customizing Starlark macro output.
///
/// This generates legacy WORKSPACE-compatible `.bzl` files with helper macros
/// for loading Maven dependencies, similar to `rules_jvm_external`'s pattern.
#[derive(Debug, Clone)]
pub struct StarlarkMacroOptions {
    /// Name of the main function that loads all dependencies (default: `"maven_dependencies"`).
    pub function_name: String,
    /// Repository URL (default: Maven Central).
    pub repository_url: String,
    /// Group artifacts by their group prefix in comments (default: true).
    pub group_by_prefix: bool,
    /// Include docstrings in the output (default: true).
    pub include_docstring: bool,
}

impl Default for StarlarkMacroOptions {
    fn default() -> Self {
        Self {
            function_name: "maven_dependencies".to_string(),
            repository_url: MAVEN_CENTRAL_URL.to_string(),
            group_by_prefix: true,
            include_docstring: true,
        }
    }
}

impl StarlarkMacroOptions {
    /// Creates new options with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the main function name.
    #[must_use]
    pub fn with_function_name(mut self, name: impl Into<String>) -> Self {
        self.function_name = name.into();
        self
    }

    /// Sets the repository URL.
    #[must_use]
    pub fn with_repository_url(mut self, url: impl Into<String>) -> Self {
        self.repository_url = url.into();
        self
    }

    /// Sets whether to group artifacts by prefix in comments.
    #[must_use]
    pub const fn with_group_by_prefix(mut self, group: bool) -> Self {
        self.group_by_prefix = group;
        self
    }

    /// Sets whether to include docstrings.
    #[must_use]
    pub const fn with_include_docstring(mut self, include: bool) -> Self {
        self.include_docstring = include;
        self
    }
}

/// Writes a lockfile to legacy WORKSPACE-compatible Starlark macro format.
///
/// Generates a `.bzl` file with:
/// - `http_jar` load statement
/// - `maybe` helper function for idempotent loading
/// - `_download` helper function for artifact downloads
/// - Main function (default: `maven_dependencies`) that loads all artifacts
///
/// # Example
///
/// ```ignore
/// use antlers_lock::{Lockfile, writer};
///
/// let lockfile = Lockfile::read_file("deps.lock.json")?;
/// let bzl = writer::write_starlark_macro(&lockfile)?;
/// std::fs::write("repositories.bzl", bzl)?;
/// ```
///
/// Usage in WORKSPACE:
///
/// ```starlark
/// load("//:repositories.bzl", "maven_dependencies")
/// maven_dependencies()
/// ```
///
/// # Errors
///
/// This function is infallible in practice as writing to a String never fails.
pub fn write_starlark_macro(lockfile: &Lockfile) -> Result<String> {
    write_starlark_macro_with_options(lockfile, &StarlarkMacroOptions::default())
}

/// Writes a lockfile to legacy WORKSPACE-compatible Starlark macro format with custom options.
///
/// # Example
///
/// ```ignore
/// use antlers_lock::{Lockfile, writer::{self, StarlarkMacroOptions}};
///
/// let lockfile = Lockfile::read_file("deps.lock.json")?;
/// let options = StarlarkMacroOptions::default()
///     .with_function_name("load_maven_jars")
///     .with_repository_url("https://maven.example.com/repo");
/// let bzl = writer::write_starlark_macro_with_options(&lockfile, &options)?;
/// ```
///
/// # Errors
///
/// This function is infallible in practice as writing to a String never fails.
#[allow(clippy::unnecessary_wraps)]
pub fn write_starlark_macro_with_options(
    lockfile: &Lockfile,
    options: &StarlarkMacroOptions,
) -> Result<String> {
    let mut output = String::new();

    // Write file header/docstring
    if options.include_docstring {
        output.push_str("\"\"\"Maven dependencies for WORKSPACE.\n\n");
        output.push_str("This file is generated by antlers. Do not edit manually.\n\n");
        output.push_str("Usage:\n");
        let _ = writeln!(
            output,
            "    load(\"//:repositories.bzl\", \"{}\")",
            options.function_name
        );
        let _ = writeln!(output, "    {}()", options.function_name);
        output.push_str("\"\"\"\n\n");
    } else {
        output.push_str("# Generated by antlers\n\n");
    }

    // Write load statement
    output.push_str("load(\"@bazel_tools//tools/build_defs/repo:http.bzl\", \"http_jar\")\n\n");

    // Write maybe helper
    write_maybe_helper(&mut output, options);
    output.push('\n');

    // Write _download helper
    write_download_helper(&mut output, options);
    output.push('\n');

    // Write main function
    write_main_function(&mut output, lockfile, options);

    Ok(output)
}

/// Writes the `maybe` helper function for idempotent rule loading.
fn write_maybe_helper(output: &mut String, options: &StarlarkMacroOptions) {
    output.push_str("def maybe(repo_rule, name, **kwargs):\n");
    if options.include_docstring {
        output
            .push_str("    \"\"\"Execute a repository rule if it hasn't been defined yet.\"\"\"\n");
    }
    output.push_str("    if name not in native.existing_rules():\n");
    output.push_str("        repo_rule(name = name, **kwargs)\n");
}

/// Writes the `_download` helper function for downloading artifacts.
fn write_download_helper(output: &mut String, options: &StarlarkMacroOptions) {
    output.push_str("def _download(name, path, sha256):\n");
    if options.include_docstring {
        output.push_str("    \"\"\"Download a Maven artifact.\"\"\"\n");
    }
    output.push_str("    maybe(\n");
    output.push_str("        http_jar,\n");
    output.push_str("        name = name,\n");
    let _ = writeln!(
        output,
        "        url = \"{}/\" + path,",
        escape_starlark(&options.repository_url)
    );
    output.push_str("        sha256 = sha256,\n");
    output.push_str("    )\n");
}

/// Writes the main function that loads all dependencies.
fn write_main_function(output: &mut String, lockfile: &Lockfile, options: &StarlarkMacroOptions) {
    let _ = writeln!(output, "def {}():", options.function_name);

    if options.include_docstring {
        let _ = writeln!(output, "    \"\"\"Load all Maven dependencies.\n");
        let _ = writeln!(output, "    This function should be called from WORKSPACE.");
        output.push_str("    \"\"\"\n");
    }

    if lockfile.artifacts.is_empty() {
        output.push_str("    pass\n");
        return;
    }

    // Sort artifacts for deterministic output
    let mut sorted_artifacts: Vec<_> = lockfile.artifacts.iter().collect();
    sorted_artifacts.sort_by(|(k1, _), (k2, _)| k1.cmp(k2));

    // Group by prefix if enabled
    let mut current_prefix = String::new();

    for (coord, artifact) in sorted_artifacts {
        // Add group comment if grouping is enabled
        if options.group_by_prefix {
            let prefix = coord
                .split(':')
                .next()
                .unwrap_or("")
                .split('.')
                .take(2)
                .collect::<Vec<_>>()
                .join(".");

            if prefix != current_prefix {
                if !current_prefix.is_empty() {
                    output.push('\n');
                }
                let _ = writeln!(output, "    # {prefix}");
                current_prefix = prefix;
            }
        }

        let target_name = coordinate_to_target_name(coord);
        let path = coordinate_to_path(coord, &artifact.version, &artifact.packaging);

        // Use serde_starlark to serialize the _download() function call
        let download_call = DownloadCall {
            name: target_name,
            path,
            sha256: artifact.sha256.clone(),
        };

        // Serialize and indent each line for proper function body formatting
        if let Ok(call_str) = serde_starlark::to_string(&download_call) {
            for line in call_str.lines() {
                let _ = writeln!(output, "    {line}");
            }
        }
    }
}

/// Converts a Maven coordinate to a Bazel target name.
///
/// This is the public version of the coordinate conversion function,
/// exposed for use by consumers who need to generate compatible target names.
///
/// # Example
///
/// ```
/// use antlers_lock::writer::starlark::coordinate_to_target_name;
///
/// assert_eq!(
///     coordinate_to_target_name("com.google.guava:guava"),
///     "com_google_guava_guava"
/// );
/// assert_eq!(
///     coordinate_to_target_name("org.jetbrains.kotlin:kotlin-stdlib"),
///     "org_jetbrains_kotlin_kotlin_stdlib"
/// );
/// ```
#[must_use]
pub fn coordinate_to_target_name(coord: &str) -> String {
    coord
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod macro_tests {
    use super::*;
    use crate::{LockedArtifact, LockfileMetadata};
    use indexmap::IndexMap;

    fn create_test_lockfile() -> Lockfile {
        let mut artifacts = IndexMap::new();
        artifacts.insert(
            "com.google.guava:guava".to_string(),
            LockedArtifact::new(
                "33.0.0-jre",
                "abc123def456789012345678901234567890123456789012345678901234",
            )
            .with_dependencies(vec!["com.google.guava:failureaccess".to_string()]),
        );
        artifacts.insert(
            "com.google.guava:failureaccess".to_string(),
            LockedArtifact::new(
                "1.0.2",
                "def456abc789012345678901234567890123456789012345678901234567",
            ),
        );
        artifacts.insert(
            "org.slf4j:slf4j-api".to_string(),
            LockedArtifact::new(
                "2.0.9",
                "789abc012345678901234567890123456789012345678901234567890123",
            ),
        );

        Lockfile {
            version: "1".to_string(),
            format: "antlers-lock".to_string(),
            artifacts,
            repositories: vec![],
            conflicts: vec![],
            metadata: LockfileMetadata::with_generator("test"),
            extensions: IndexMap::new(),
        }
    }

    #[test]
    fn test_write_starlark_macro_basic() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_macro(&lockfile).unwrap();

        // Check docstring
        assert!(output.contains("\"\"\"Maven dependencies for WORKSPACE."));
        assert!(output.contains("generated by antlers"));

        // Check load statement
        assert!(
            output.contains("load(\"@bazel_tools//tools/build_defs/repo:http.bzl\", \"http_jar\")")
        );

        // Check maybe helper
        assert!(output.contains("def maybe(repo_rule, name, **kwargs):"));
        assert!(output.contains("native.existing_rules()"));

        // Check _download helper
        assert!(output.contains("def _download(name, path, sha256):"));
        assert!(output.contains("https://repo1.maven.org/maven2"));

        // Check main function
        assert!(output.contains("def maven_dependencies():"));
    }

    #[test]
    fn test_write_starlark_macro_artifacts() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_macro(&lockfile).unwrap();

        // Check artifact downloads
        assert!(output.contains("name = \"com_google_guava_guava\""));
        assert!(output.contains("name = \"com_google_guava_failureaccess\""));
        assert!(output.contains("name = \"org_slf4j_slf4j_api\""));

        // Check paths
        assert!(
            output.contains("path = \"com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar\"")
        );
        assert!(
            output.contains(
                "path = \"com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar\""
            )
        );

        // Check sha256
        assert!(output.contains("sha256 = \"abc123def456"));
    }

    #[test]
    fn test_write_starlark_macro_grouping() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_macro(&lockfile).unwrap();

        // Check group comments
        assert!(output.contains("# com.google"));
        assert!(output.contains("# org.slf4j"));
    }

    #[test]
    fn test_write_starlark_macro_no_grouping() {
        let lockfile = create_test_lockfile();
        let options = StarlarkMacroOptions::default().with_group_by_prefix(false);
        let output = write_starlark_macro_with_options(&lockfile, &options).unwrap();

        // Should not have group comments
        assert!(!output.contains("# com.google"));
        assert!(!output.contains("# org.slf4j"));
    }

    #[test]
    fn test_write_starlark_macro_custom_function_name() {
        let lockfile = create_test_lockfile();
        let options = StarlarkMacroOptions::default().with_function_name("load_jars");
        let output = write_starlark_macro_with_options(&lockfile, &options).unwrap();

        assert!(output.contains("def load_jars():"));
        assert!(output.contains("load_jars()"));
    }

    #[test]
    fn test_write_starlark_macro_custom_repo() {
        let lockfile = create_test_lockfile();
        let options =
            StarlarkMacroOptions::default().with_repository_url("https://maven.example.com/repo");
        let output = write_starlark_macro_with_options(&lockfile, &options).unwrap();

        assert!(output.contains("url = \"https://maven.example.com/repo/\""));
    }

    #[test]
    fn test_write_starlark_macro_no_docstring() {
        let lockfile = create_test_lockfile();
        let options = StarlarkMacroOptions::default().with_include_docstring(false);
        let output = write_starlark_macro_with_options(&lockfile, &options).unwrap();

        assert!(!output.contains("\"\"\"Maven dependencies for WORKSPACE."));
        assert!(output.contains("# Generated by antlers"));
    }

    #[test]
    fn test_write_starlark_macro_empty_lockfile() {
        let lockfile = Lockfile::new();
        let output = write_starlark_macro(&lockfile).unwrap();

        assert!(output.contains("def maven_dependencies():"));
        assert!(output.contains("pass"));
    }

    #[test]
    fn test_coordinate_to_target_name() {
        assert_eq!(
            coordinate_to_target_name("com.google.guava:guava"),
            "com_google_guava_guava"
        );
        assert_eq!(
            coordinate_to_target_name("org.jetbrains.kotlin:kotlin-stdlib"),
            "org_jetbrains_kotlin_kotlin_stdlib"
        );
        assert_eq!(
            coordinate_to_target_name("io.grpc:grpc-core"),
            "io_grpc_grpc_core"
        );
    }

    #[test]
    fn test_starlark_macro_syntax_valid() {
        let lockfile = create_test_lockfile();
        let output = write_starlark_macro(&lockfile).unwrap();

        // Check balanced parentheses
        let open_parens = output.matches('(').count();
        let close_parens = output.matches(')').count();
        assert_eq!(open_parens, close_parens);

        // Check all _download calls have proper structure
        for line in output.lines() {
            if line.contains("_download(") {
                // Each _download call should be followed by proper arguments
                assert!(output.contains("name ="));
                assert!(output.contains("path ="));
                assert!(output.contains("sha256 ="));
            }
        }
    }
}
