//! Bazel output formatter.

use std::fmt::Write as _;

use antlers_lock::Lockfile;

use crate::output::{artifact_from_locked, coordinates_from_key};
use crate::{FormatOptions, Result};

/// Outputs a BUILD file with `java_import` rules.
pub fn format(lockfile: &Lockfile, _options: &FormatOptions) -> Result<String> {
    let mut output = String::new();
    output.push_str("# Generated by antlers-resolve\n\n");
    output.push_str("package(default_visibility = [\"//visibility:public\"])\n\n");

    for (coord, locked) in &lockfile.artifacts {
        let coords = coordinates_from_key(coord)?;
        let artifact = artifact_from_locked(&coords, locked);
        let name = bazel_name(coord);

        let _ = write!(
            output,
            "java_import(\n    name = \"{name}\",\n    jars = [\"{}\"],\n",
            artifact.repository_path()
        );

        if !locked.dependencies.is_empty() {
            output.push_str("    deps = [\n");
            for dep in &locked.dependencies {
                let _ = writeln!(output, "        \":{}\",", bazel_name(dep));
            }
            output.push_str("    ],\n");
        }

        output.push_str(")\n\n");
    }

    Ok(output)
}

fn bazel_name(coord: &str) -> String {
    coord.replace([':', '.', '-'], "_")
}
