//! Buck2 output formatter.

use std::fmt::Write as _;

use antlers_lock::Lockfile;

use crate::output::{artifact_from_locked, checksum_or_none, coordinates_from_key};
use crate::{Error, FormatOptions, Result};

/// Outputs BUCK file rules for resolved artifacts.
pub fn format(lockfile: &Lockfile, options: &FormatOptions) -> Result<String> {
    let mut output = String::new();
    output.push_str("# Generated by antlers-resolve\n");
    output.push_str("# https://github.com/albertocavalcante/antler\n\n");

    let mut skipped = 0;

    for (coord, locked) in &lockfile.artifacts {
        let coords = coordinates_from_key(coord)?;
        let artifact = artifact_from_locked(&coords, locked);

        let Some(checksum) = checksum_or_none(locked) else {
            if options.strict {
                return Err(Error::MissingChecksum(coord.clone()));
            }
            skipped += 1;
            let _ = writeln!(output, "# SKIPPED: {coord} - no checksum available\n");
            continue;
        };

        let name = coords.artifact_id.replace(['-', '.'], "_");
        let mvn_url = buck_mvn_url(&artifact);

        let _ = write!(
            output,
            r#"# {coord}
remote_file(
    name = "{name}_jar",
    out = "{}",
    sha256 = "{checksum}",
    url = "{mvn_url}",
)

prebuilt_jar(
    name = "{name}",
    binary_jar = ":{name}_jar",
    visibility = ["PUBLIC"],
)

"#,
            artifact.filename(),
        );
    }

    if skipped > 0 {
        let _ = writeln!(
            output,
            "# NOTE: {skipped} artifact(s) skipped due to missing checksums"
        );
    }

    Ok(output)
}

fn buck_mvn_url(artifact: &gav::Artifact) -> String {
    let extension = artifact.extension.as_str();
    artifact.classifier.as_ref().map_or_else(
        || {
            format!(
                "mvn:{}:{}:{}:{}",
                artifact.group_id(),
                artifact.artifact_id(),
                extension,
                artifact.version
            )
        },
        |classifier| {
            format!(
                "mvn:{}:{}:{}:{}:{}",
                artifact.group_id(),
                artifact.artifact_id(),
                extension,
                artifact.version,
                classifier.0
            )
        },
    )
}
