//! Starlark output formatter.

use std::fmt::Write as _;

use antlers_lock::Lockfile;

use crate::output::{
    artifact_download_url, artifact_from_locked, checksum_or_none, coordinates_from_key,
    escape_starlark,
};
use crate::{Error, FormatOptions, Result};

/// Outputs a `.bzl` file containing a `MAVEN_ARTIFACTS` dict.
pub fn format(lockfile: &Lockfile, options: &FormatOptions) -> Result<String> {
    let mut output = String::new();
    output.push_str("# Generated by antlers-resolve\n\n");
    let _ = writeln!(
        output,
        "WORKSPACE_NAME = \"{}\"\n",
        escape_starlark(&options.workspace_name)
    );
    output.push_str("MAVEN_ARTIFACTS = {\n");

    let mut skipped = 0;

    for (coord, locked) in &lockfile.artifacts {
        let coords = coordinates_from_key(coord)?;
        let artifact = artifact_from_locked(&coords, locked);

        let Some(checksum) = checksum_or_none(locked) else {
            if options.strict {
                return Err(Error::MissingChecksum(coord.clone()));
            }
            skipped += 1;
            let _ = writeln!(output, "    # SKIPPED: {coord} - no checksum available");
            continue;
        };

        let url = artifact_download_url(lockfile, &artifact, locked);

        let _ = writeln!(output, "    \"{}\": {{", escape_starlark(coord));
        let _ = writeln!(
            output,
            "        \"version\": \"{}\",",
            escape_starlark(&artifact.version.to_string())
        );
        let _ = writeln!(
            output,
            "        \"sha256\": \"{}\",",
            escape_starlark(checksum)
        );
        let _ = writeln!(output, "        \"url\": \"{}\",", escape_starlark(&url));

        if locked.dependencies.is_empty() {
            output.push_str("        \"deps\": [],\n");
        } else {
            output.push_str("        \"deps\": [\n");
            for dep in &locked.dependencies {
                let _ = writeln!(output, "            \"{}\",", escape_starlark(dep));
            }
            output.push_str("        ],\n");
        }

        output.push_str("    },\n");
    }

    output.push_str("}\n");

    if skipped > 0 {
        let _ = writeln!(
            output,
            "\n# NOTE: {skipped} artifact(s) skipped due to missing checksums"
        );
    }

    Ok(output)
}
